# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-18 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='desc',
            new_name='description',
        ),
    ]
